### ISSUE TITLE
fusion with stereo camera ?

### ISSUE THREAD

**Issue by mahammadirfan** [JokerJohn/LIO-SAM-6AXIS-INTENSITY#2]
Hi,
Thanks for the nice work. I am wondering if we can integrate this with a stereo camera ?

**Comment by JokerJohn** [comment]
@mahammadirfan Unfortunately, if you are looking to introduce a visual loop closure based on image detection in the system, similar to intensity detection, **I believe it is not quite supported.** For visual loop closures like those in VINS-fusion, it involves not only 2D feature point matching but also the removal of outliers through **2D-3D RANSAC** to achieve better loop closure matching results, this module is essential. The 3D points corresponding to 2D image feature points in the image are calculated through triangulation during the VIO tracking process and are continuously optimized and updated. This means **you need to further incorporate the entire VIO estimator module**, which would significantly degrade the overall system performance. Intensity detection is feasible in this repo because the intensity image and the point cloud range image have the exact same dimensions (2048*128), and each feature point on the range image has a corresponding laser 3D point, allowing for 2D-3D RANSAC.

**Comment by mahammadirfan** [comment]
Thanks for your valuable reply.
I get your point now. I am working in a project where i need to fuse ouster lidar,stereo camera,imu,gps,....any thoughts for slam based fusion of this sensors ? can you suggest any algorithms ?
THanks

**Comment by JokerJohn** [comment]
@mahammadirfan For the overall accuracy of the system, I suggest that LIO+GNSS is sufficient. You can refer to the results of the HILTI competition, where the best accuracy was still achieved with LIO, not LVIO. This is because the stability of LIDAR sensors is far superior to cameras, and often the introduction of cameras reduces the overall performance of LIO. However, if you are looking to improve robustness, you might consider incorporating cameras. For a recommended LVIO algorithm repository, you can check out FAST-LVIO.

**Comment by mahammadirfan** [comment]
@JokerJohn Thank you for your suggestions and reply. cheers!
